### ISSUE TITLE
How to uninstall chat-gpt desktop app from linux

### ISSUE THREAD

**Issue by syedfahdali** [danigbaameiro/ChatGPT-Desktop#1]
I have tried your app but it does not work in my case so that is why i am uninstalling it.

**Comment by Sawyer13** [comment]
Hi @syedfahdali ! 

Sadly to hear that 😔

Could you tell me your distribution in order to help you? I just tried to reinstall it on an ubuntu 22.04 and it works correctly (29/06/2023).

Uninstalling it is simple. If you have not copied the binary to the /usr path, deleting the repository is fine. When you run "npm" a new folder is created but over the repository path. 

I hope I helped you, 
Cheers

**Comment by danigbaameiro** [comment]
As there is no answer, i'm going to close this issue. 

Thanks for the feedback @syedfahdali :)
